### PR TITLE
 Rename Tiled Gridded Elevation Data conformance class 

### LINKED ISSUE #46: Rename Tiled Gridded Elevation Data conformance class
Remove 'Tiled Gridded Elevation Data' from the welcome page 
http://cite.opengeospatial.org/te2/about/gpkg12/1.2/site/

### PR DESCRIPTION
**Pull request by lgoltz**
Fixes #46

### CODE REVIEW

**Review by bosborn — COMMENTED** [review]
In TiledGriddedCoverageTests.java:

* "gpkg_elevation_tiles" needs to be changed to "gpkg_2d_gridded_coverage" in 4 places
* "http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data" needs to be changed to "http://docs.opengeospatial.org/is/17-066r1/17-066r1.html" in 3 places

**Comment by lgoltz** [comment]
@bosborn Thanks for verifcation! 
I think in http://docs.opengeospatial.org/is/17-066r1/17-066r1.html#_extensions the Test Method "4. For each table_name" must be fixed as well?

Currently the SQL statement is
```
SELECT column_name, definition, scope from gpkg_extensions 
  WHERE extension_name = gpkg_elevation_tiles AND table_name = {table_name}
```

But it should be 
```
SELECT column_name, definition, scope from gpkg_extensions 
  WHERE extension_name = gpkg_2d_gridded_coverage AND table_name = {table_name}
```

**Comment by lgoltz** [comment]
@bosborn Can you also take a look at test `requiredSRSReferences`? I'm wondering if the test is correct and which test case or requirement is covered, I cannot find a test case with id `/opt/extensions/elevation/srs/required_references` in http://docs.opengeospatial.org/is/17-066r1/17-066r1.html

**Comment by bosborn** [comment]
I agree with your comment on Test Method "4. For each table_name".

For `requiredSRSReferences`, it looks like the test id should probably be: _/extensions/elevation/table_val/gpkg_spatial_ref_sys/refs_ which says it tests requirement 4.

> Requirement 4 | Req/gpkg-spatial-ref-sys-record
The gpkg_spatial_ref_sys table in a GeoPackage SHALL contain records to define all spatial reference systems used by tiled gridded data in a GeoPackage. The spatial reference system SHALL be used to define the vertical datum, reference geoid, and units of measure for the tiled gridded elevation data.

The `requiredSRSReferences()` method looks to test the SRS reference like the test case claims.

> Verify that all elevation data uses an SRS that is defined in gpkg_spatial_ref_sys

The Test Case _Test Method_ might not be correct.  It appears to only check that tile matrix set entries exist for contents of type _2d-gridded-coverage_.

```
1. SELECT table_name FROM gpkg_contents WHERE data_type = 2d-gridded-coverage;
2. For each table_name
    a. SELECT COUNT(*) FROM gpkg_tile_matrix_set WHERE table_name = {table_name}
    b. Fail if count is not 1
3. Pass if no fails
```

Thoughts @jyutzler?

**Comment by dstenger** [comment]
I propose to add all previous discussed changes to this pull request but to move the discussion in https://github.com/opengeospatial/ets-gpkg12/pull/48#issuecomment-378954992 to a new issue.

**Comment by dstenger** [comment]
> "gpkg_elevation_tiles" needs to be changed to "gpkg_2d_gridded_coverage" in 4 places

Done: https://github.com/opengeospatial/ets-gpkg12/pull/48/commits/20bc7faa89895403f0325c900ec88360c18aa0ec

> "http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data" needs to be changed to "http://docs.opengeospatial.org/is/17-066r1/17-066r1.html" in 3 places

Done: https://github.com/opengeospatial/ets-gpkg12/pull/48/commits/02d3c82539bd23f1416b9ac592433795db2eb6c5

**Comment by dstenger** [comment]
@bosborn Can you please review and confirm that all changes have been done now?

I will create a new issue for test ```requiredSRSReferences``` when merging this pull request.

**Comment by bosborn** [comment]
Looks good. Two test GeoPackages need updated to the new gpkg_extensions extension_name and definition values.  I created PR #49 (just to your PR branch) with those updated.

**Comment by lgoltz** [comment]
> I will create a new issue for test requiredSRSReferences when merging this pull request.

Created #51

**Pull request merged**
