### PR TITLE
updating comments and links therein

### PR DESCRIPTION
**Pull request by jyutzler**
This improves the alignment of the ETS with the actual requirements.
#51

### CODE REVIEW

**Comment by lgoltz** [comment]
@jyutzler You changed "elevation" to "coverage" in the test cases. As far as I see in http://docs.opengeospatial.org/is/17-066r1/17-066r1.html "elevation" seems to be correct (e.g. "/extensions/elevation/table_def/gpkg_2d_gridded_coverage_ancillary" in [A.1.1  Coverage Ancillary](http://docs.opengeospatial.org/is/17-066r1/17-066r1.html#_coverage_ancillary).

Furthermore in the ATS the test for Requirement 4 has the test case ID "/extensions/elevation/table_val/gpkg_spatial_ref_sys/refs", in the Java Doc it is "/opt/extensions/coverage/srs/required_references".

**Comment by dstenger** [comment]
@jyutzler Can you please take a look a the comment of lgoltz?

**Comment by jyutzler** [comment]
"elevation" is an error in the standard. If we issue a corrigendum, those values will be updated.

**Comment by dstenger** [comment]
@jyutzler 
Thus, the change from "elevation" to "coverage" is fine, right?

Java Doc for Requirement 4 should be updated if you agree.

**Comment by jyutzler** [comment]
I swept the file for extraneous uses of "elevation". Should be good now.

**Pull request merged**
