### PR TITLE
I52

### LINKED ISSUE #52: ETS fails on poorly named contents tables
If someone naively names a content table something like `0`, most of the tests will break because `SELECT * FROM 0` is not valid SQL - the `0` needs to be escaped like `select * from '0'`. We need to sweep through the entire ETS to eliminate instances of unescaped table names.

### PR DESCRIPTION
**Pull request by jyutzler**
Addresses #52, but only for tiles

Fixes #52.

### CODE REVIEW

**Comment by jyutzler** [comment]
Not sure but maybe you want to rebase the middle commits since the original test file was 50MB which is a bit too big.

**Comment by dstenger** [comment]
@keshav-nangare Can you please remove the test file > 50MB from commit history?

**Comment by keshavnangare** [comment]
I fetched this branch locally but didn't get any git warnings or the file related issue.

@jyutzler 

Did you get any git warnings or other issue related to big file?

You already deleted the big .gpkg file with name "imagery-0.gpkg" and added smaller one. Right?

**Comment by jyutzler** [comment]
@keshav-nangare 
When I added the file originally, I got a warning message from GitHub.  I deleted the big file and readded a smaller one, but I don't know if that fixed the problem. Perhaps it did.

**Comment by jyutzler** [comment]
Today's changes now include a new test case for features. The problem could potentially still exist in extensions.

**Comment by dstenger** [comment]
@jyutzler Can you undo all commits and create a new one? This should fix the problem. Otherwise, the file is still existing in history.

**Comment by dstenger** [comment]
There is a second >50MB file in the repository: haiti-vectors-split.gpkg

This should be removed as well. As this is a more complex task, I created a new issue for that: #56

**Review by dstenger — APPROVED** [review]
Fixes issue as described in #52.

**Pull request merged**
