### PR TITLE
Feature tests handling almost all of the geometry blob information

### PR DESCRIPTION
**Pull request by ajanett**
featureSRSconsistency - Test extending 13 which is currently only looking at table definitions, but if one inspects the standard, there are additional tests such as inconsistencies between srs_id that need to be examined.  The feature portion of this test has been added to check for inconsistencies between the geopackage contents, the geopackage geometry columns, and the set of srs_id and feature tables.

getFeaturesWithGeometryInfo - Iterator for processing feature geometry tests. This iterator performs the baseline query needed for all feature geometry tests, gathering the gpkg_geometry_columns values that will be checked for consistency against the geometry blob content in each feature.  By processing these tests with the iterator, we can check for errors in each feature table and not just quit at the very first error found.

featureGeometryEncodingTesting – Called by the iterator for each feature table, this test function performs all testing against the geometry blob for each row of the feature table. In order to maintain some processing performance, all of these tests have to be done here rather than re-process the blob for each test separately. The tests do attempt to re-use previously identified data. Each test performed within this group provides a detailed response if an issue is found. Reviewing the tests in here:
19 i   Looks for the correct magic number
19 ii  Looks for the correct version number
19 iii Verifies the binary type
19 iv  Verifies the correct envelope flag values
33     Verifies the srs_id. This test also will check for byte swap errors within the srs_id, hence by putting the test before 19 v, it will catch potential byte swap errors that may affect retrieval of the envelope.
19 v   If the geometry is empty but the envelope is not empty, triggers an error
20     Verifies the geometry type from within the WKB. This test also will check for possible byte swap errors within the WKB.
32	Checks if the WKB geometry type (subtype) is allowed based on the geometry type provided by gpkg_geometry_columns.
66	Partial – included only a check on the WKB item count value (when applicable) at this time. WKB processing is going to suck down a huge amount of processing time!
67	Check for gpkg_extensions for gpkg_geom_<feature> for the feature (when there are extensions).
NSG 19B Ensure the geopackage extents from gpkg_geometry_columns contains the feature envelope.
78	Verify that the rtree trigger accurately contains the feature envelope when there are rtree extensions

featureGeometryColumnsDataValuesTableNameNEW – Added because it does not appear that the existing tests for 23 and 26 are compliant with OGC 12-128r14.

Also:
Clean up of escaped single quotes in SQL statements.

### CODE REVIEW

**Comment by ajanett** [comment]
These code changes may fail to pass the current tests as the current test geopackage(s) may have some issues that these new tests are detecting.  For instance, feature-0.gpkg extents does not contain the envelope of the geometry specified by feature 0. The attached feature-0_FIXED.gpkg has updated extents and does not exhibit the issue.
[features-0_FIXED.zip](https://github.com/opengeospatial/ets-gpkg12/files/2056251/features-0_FIXED.zip)

**Comment by ajanett** [comment]
Test GeoPackages with failure and pass conditions for these code updates are provided here. 
[testCases.zip](https://github.com/opengeospatial/ets-gpkg12/files/2056256/testCases.zip)

**Comment by bermud** [comment]
@ajanett, thank you for this pull request! Can you please cross reference (mentioned)  any issues that are currently opened?
@jyutzler , @dstenger, I  suggest to include the test cases and test files as part of the code structure. Any change that we do in the future can be verified against these test cases.

**Comment by ajanett** [comment]
This pull request addresses issue #60 

It also addressed the geopackage ETS code for: geopackage/issues/443, 442, and the feature portion of 444
https://github.com/opengeospatial/geopackage/issues/443
https://github.com/opengeospatial/geopackage/issues/442
https://github.com/opengeospatial/geopackage/issues/444

**Comment by ajanett** [comment]
This pull request also addresses https://github.com/opengeospatial/ets-gpkg12-nsg/issues/10
in part as the nsg geopackage functionality is to be removed and it is instead handled here.

**Comment by dstenger** [comment]
@jyutzler Can you confirm that failure documented in https://github.com/opengeospatial/ets-gpkg12/pull/62#issuecomment-393370695 is correct?

@ajanett Test files provided in https://github.com/opengeospatial/ets-gpkg12/pull/62#issuecomment-393371593 are not integrated in tests, right? Can we integrate those test files to tests of test suite?

**Comment by ajanett** [comment]
@jyutzler  Yes, The OGC team may use any of the test files provided in this thread. You are correct in that I have not integrated the tests and you may certainly do that.  I've been seeing many GeoPackages that have extents of insufficient size to cover the GeoPackage content, and this failure is one of them. For this correction, I simply adjusted the SQL extents sufficiently to represent the feature content.

**Comment by dstenger** [comment]
@jyutzler 
This pull request modifies several existing tests.
Can you please review those changes and confirm if they are OK from your side of view?

**Comment by jyutzler** [comment]
This is bubbling up to the top of my priorities list.

**Comment by ajanett** [comment]
@jyutzler  Thanks, I'll go pull from the mainline.

**Pull request merged**
