### PR TITLE
Corrections in support of passing Fortify tests.

### LINKED ISSUE #83: Fortify Scan Issues
Fortify Scan issues are present in this test package. I will submit a pull request with corrections shortly.

Details:
ets-gpkg12-0.7 Release

CWE ID 022  - External input in the construction of a pathname that is not verified.
TestNGController.java line 80 
TestRunArguments.java line 42

CDW ID 089 - SQL Injection due to use of external components in the creation of the SQL command that are not verified.
CommonFixture.java line 181, 225, 291
NonLinearTests.java line 160
TableVerifier.java line 82, 184
DataContentsTests.java line 75
ExtensionsTests.java line 177
TiledGriddedCoverageTests.java lines 268, 381, 502, 510
RTreeIndexTests.java, lines 135, 148, 162, 211
SchemaTests.java, lines 190, 326
FeaturesTests.java, lines 1231, 1293, 1476, 1519

### PR DESCRIPTION
**Pull request by ajanett**
Supports corrections needed to this ets so that it will pass Fortify tests as indicated in Issue #83 

Fixes #83.

### CODE REVIEW

**Comment by dstenger** [comment]
@ajanett Thank you for the pull request. Can you please try to resolve the merge conflicts.

**Comment by ajanett** [comment]
@dstenger Sure. I'll take a look. Shouldn't be difficult, just a matter of fitting it into the schedule.

**Comment by ajanett** [comment]
@dstenger  Tried to resolve those conflicts, though there was really only one and it wasn't actually a conflict. Hope this helps!

**Comment by lgoltz** [comment]
@ajanett The methods ValidateSQLiteTableColumnStringInput and cleanCharSQLite seems to be duplicates. Can they moved to to the class TableVerifier? 
And please change the first letter of the methods to lowercase, as this is the code convention in java.

**Pull request merged**
