### PR TITLE
nsg test enhancements

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jyutzler** [comment]
@melvchan Are there any sample files that can be used to show these new tests being exercised? I didn't see any substantive changes to src/test/java/org/opengis/cite/gpkg12/VerifyTestNGController.java.

**Comment by ghost** [comment]
@jyutzler 

[AGC_NAIP_DonaAnaRange_NM_13_16_10_11MAY2017.zip](https://github.com/opengeospatial/ets-gpkg12/files/1607233/AGC_NAIP_DonaAnaRange_NM_13_16_10_11MAY2017.zip)

Below is the testng results for the image above - only testing NSG. It passes all but one.

 
[testng-results.zip](https://github.com/opengeospatial/ets-gpkg12/files/1607242/testng-results.zip)

**Comment by jyutzler** [comment]
@melvchan How big is this test file? If it is not too big, add it to src/test/resources/gpkg and add a line for it in VerifyTestNGController.java.

**Comment by ghost** [comment]
@jyutzler I finished adding it as a unit test case, ready for review. 
https://github.com/opengeospatial/ets-gpkg12/pull/35/commits/dec824cf9fa1399dc0e2dc95db354da141b7825b

**Comment by jyutzler** [comment]
I'm going to have to take a look at this more closely. I don't like the idea of these new conformance classes triggering test failures that were not there before.

**Comment by ghost** [comment]
@jyutzler If you're referring to the part where the number increased like the example below, runTests(ClassLoader.getSystemResource("gpkg/gdal_sample_v1.2_spi_nonlinear_webp_elevation.gpkg"), 6);


then I believe those test failures were only there because NSG was specified in the test-runs-props.xml. I suppose it's because the unit test wants to test all cases, but in the user scenario, if they choose to skip the NSG test portion, then those errors won't show up for them.

**Comment by jyutzler** [comment]
Perhaps we can tweak the way the tests are run to only execute the NSG tests for files that are designed with the NSG Profile in mind. Nevertheless, people aren't going to be happy if previously-compliant files suddenly become non-compliant. This is why I need to take a closer look.

**Comment by bermud** [comment]
Maybe the NSG GeoPackage conformance class should be moved to another project. Profiles usually live in their own repositories.

**Comment by jyutzler** [comment]
Separate repository being created.

**Comment by bermud** [comment]
Repository was created here https://github.com/opengeospatial/ets-gpkg12-nsg.

**Pull request closed without merging**
